name: 7-Move Changed Notebooks to Databricks

on:
  push:
    branches: [main]

jobs:
  move-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://install.databricks.com/cli/debian/databricks-cli_0.17.0_amd64.deb -o databricks-cli.deb
          sudo dpkg -i databricks-cli.deb

      - name: Configure Databricks CLI
        run: |
          databricks configure --token ${{ secrets.DATABRICKS_TOKEN }} --host ${{ secrets.DATABRICKS_URL }}

      - name: Determine Changed Notebooks
        id: changed-notebooks
        run: |
          git diff --name-only --diff-filter=AD ${GITHUB_REF} origin/main | grep '\.ipynb' > changed_notebooks.txt

      - name: Move Changed Notebooks
        if: steps.changed-notebooks.outputs.changed_notebooks != ''
        run: |
          while IFS= read -r notebook_path; do
            databricks workspace import --path $notebook_path --destination /Workspace/Shared/test-dbx-devops
          done < changed_notebooks.txt

      - name: Cleanup
        run: rm changed_notebooks.txt
