name: 7-Move Changed Notebooks to Databricks

on:
  push:
    branches: [main]

jobs:
  move-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Install Requests with Specific Versions (Looser urllib3)
        run: |
          pip install requests==2.28.1 urllib3>=1.21.1

      - name: Configure Databricks CLI
        run: |
          databricks configure --token ${{ secrets.DATABRICKS_TOKEN }} --host ${{ secrets.DATABRICKS_HOST }}

      - name: Determine Changed Notebooks
        id: changed-notebooks
        run: |
          git diff --name-only --diff-filter=AD ${GITHUB_REF} origin/main | grep '\.ipynb' > changed_notebooks.txt

      - name: Move Changed Notebooks
        if: steps.changed-notebooks.outputs.changed_notebooks != ''
        run: |
          while IFS= read -r notebook_path; do
            databricks workspace import --path $notebook_path --destination /Workspace/Shared/test-dbx-devops/
          done < changed_notebooks.txt

      - name: Cleanup
        run: rm changed_notebooks.txt
