name: List changed Python files

on:
  push:
    branches: [ main ]

jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tj-actions/changed-files@v10
        id: changed-files
        with:
          files: 'notebooks/*.py'

      - name: Print changed Python files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
