name: List Changed Python Files

on:
  push:
    branches:
      - main  # Adjust as needed
  pull_request:
    branches:
      - main  # Adjust as needed

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Changed Python Files
        run: |
          echo "Changed Python files in the 'notebooks' directory:"
          git diff --name-only HEAD^ HEAD -- notebooks/*.py || echo "No changes in Python files."
