name: List Modified Python Notebooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  list-modified-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List modified Python notebooks
        run: |
          git diff --name-only --diff-filter=ACMRTUXB $(git merge-base HEAD origin/main) HEAD notebooks/*.py
