name: List Changed Python Files

on:
  push:
    branches:
      - main  # Adjust as needed
  pull_request:
    branches:
      - main  # Adjust as needed

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Changed Python Files
        run: |
          echo "Changed Python files in the 'notebooks' directory:"

          # Check if there is a previous commit
          if git rev-parse --verify HEAD^ &>/dev/null; then
            git diff --name-only HEAD^ HEAD -- notebooks/*.py || echo "No changes in Python files."
          else
            # If there is no previous commit, check for changes in the working directory
            git diff --name-only -- notebooks/*.py || echo "No changes in Python files."
          fi
