name: List Modified Python Notebooks in Main Branch

on:
  push:
    branches: [main]

jobs:
  list-modified-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Fetch the last two commits on the main branch

      - name: List modified Python notebooks
        run: |
          git diff --name-only --diff-filter=ACMRTUXB $(git merge-base HEAD^ HEAD) HEAD notebooks/*.py
